//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace frmregistration.Server2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdditemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddcustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddadminOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddmakeupartistOperationCompleted;
        
        private System.Threading.SendOrPostCallback isvalidcustOperationCompleted;
        
        private System.Threading.SendOrPostCallback isvalidadminOperationCompleted;
        
        private System.Threading.SendOrPostCallback isvalidmakeOperationCompleted;
        
        private System.Threading.SendOrPostCallback copyproductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculatediscountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_productsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::frmregistration.Properties.Settings.Default.frmregistration_Server2_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event AdditemsCompletedEventHandler AdditemsCompleted;
        
        /// <remarks/>
        public event AddcustomerCompletedEventHandler AddcustomerCompleted;
        
        /// <remarks/>
        public event AddadminCompletedEventHandler AddadminCompleted;
        
        /// <remarks/>
        public event AddmakeupartistCompletedEventHandler AddmakeupartistCompleted;
        
        /// <remarks/>
        public event isvalidcustCompletedEventHandler isvalidcustCompleted;
        
        /// <remarks/>
        public event isvalidadminCompletedEventHandler isvalidadminCompleted;
        
        /// <remarks/>
        public event isvalidmakeCompletedEventHandler isvalidmakeCompleted;
        
        /// <remarks/>
        public event copyproductsCompletedEventHandler copyproductsCompleted;
        
        /// <remarks/>
        public event calculatediscountCompletedEventHandler calculatediscountCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event get_productsCompletedEventHandler get_productsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Additems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Additems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productcategory, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productcompany, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string productprice) {
            this.Invoke("Additems", new object[] {
                        productname,
                        productcategory,
                        productcompany,
                        productprice});
        }
        
        /// <remarks/>
        public void AdditemsAsync(string productname, string productcategory, string productcompany, string productprice) {
            this.AdditemsAsync(productname, productcategory, productcompany, productprice, null);
        }
        
        /// <remarks/>
        public void AdditemsAsync(string productname, string productcategory, string productcompany, string productprice, object userState) {
            if ((this.AdditemsOperationCompleted == null)) {
                this.AdditemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdditemsOperationCompleted);
            }
            this.InvokeAsync("Additems", new object[] {
                        productname,
                        productcategory,
                        productcompany,
                        productprice}, this.AdditemsOperationCompleted, userState);
        }
        
        private void OnAdditemsOperationCompleted(object arg) {
            if ((this.AdditemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdditemsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Addcustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Addcustomer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address) {
            this.Invoke("Addcustomer", new object[] {
                        name,
                        password,
                        phone,
                        address});
        }
        
        /// <remarks/>
        public void AddcustomerAsync(string name, string password, string phone, string address) {
            this.AddcustomerAsync(name, password, phone, address, null);
        }
        
        /// <remarks/>
        public void AddcustomerAsync(string name, string password, string phone, string address, object userState) {
            if ((this.AddcustomerOperationCompleted == null)) {
                this.AddcustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddcustomerOperationCompleted);
            }
            this.InvokeAsync("Addcustomer", new object[] {
                        name,
                        password,
                        phone,
                        address}, this.AddcustomerOperationCompleted, userState);
        }
        
        private void OnAddcustomerOperationCompleted(object arg) {
            if ((this.AddcustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddcustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Addadmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Addadmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address) {
            this.Invoke("Addadmin", new object[] {
                        name,
                        password,
                        phone,
                        address});
        }
        
        /// <remarks/>
        public void AddadminAsync(string name, string password, string phone, string address) {
            this.AddadminAsync(name, password, phone, address, null);
        }
        
        /// <remarks/>
        public void AddadminAsync(string name, string password, string phone, string address, object userState) {
            if ((this.AddadminOperationCompleted == null)) {
                this.AddadminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddadminOperationCompleted);
            }
            this.InvokeAsync("Addadmin", new object[] {
                        name,
                        password,
                        phone,
                        address}, this.AddadminOperationCompleted, userState);
        }
        
        private void OnAddadminOperationCompleted(object arg) {
            if ((this.AddadminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddadminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Addmakeupartist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Addmakeupartist([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string address) {
            this.Invoke("Addmakeupartist", new object[] {
                        name,
                        password,
                        phone,
                        address});
        }
        
        /// <remarks/>
        public void AddmakeupartistAsync(string name, string password, string phone, string address) {
            this.AddmakeupartistAsync(name, password, phone, address, null);
        }
        
        /// <remarks/>
        public void AddmakeupartistAsync(string name, string password, string phone, string address, object userState) {
            if ((this.AddmakeupartistOperationCompleted == null)) {
                this.AddmakeupartistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddmakeupartistOperationCompleted);
            }
            this.InvokeAsync("Addmakeupartist", new object[] {
                        name,
                        password,
                        phone,
                        address}, this.AddmakeupartistOperationCompleted, userState);
        }
        
        private void OnAddmakeupartistOperationCompleted(object arg) {
            if ((this.AddmakeupartistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddmakeupartistCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isvalidcust", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isvalidcust([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isvalidcustResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isvalidcustResultSpecified) {
            object[] results = this.Invoke("isvalidcust", new object[] {
                        username,
                        password});
            isvalidcustResult = ((bool)(results[0]));
            isvalidcustResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isvalidcustAsync(string username, string password) {
            this.isvalidcustAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isvalidcustAsync(string username, string password, object userState) {
            if ((this.isvalidcustOperationCompleted == null)) {
                this.isvalidcustOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisvalidcustOperationCompleted);
            }
            this.InvokeAsync("isvalidcust", new object[] {
                        username,
                        password}, this.isvalidcustOperationCompleted, userState);
        }
        
        private void OnisvalidcustOperationCompleted(object arg) {
            if ((this.isvalidcustCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isvalidcustCompleted(this, new isvalidcustCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isvalidadmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isvalidadmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isvalidadminResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isvalidadminResultSpecified) {
            object[] results = this.Invoke("isvalidadmin", new object[] {
                        username,
                        password});
            isvalidadminResult = ((bool)(results[0]));
            isvalidadminResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isvalidadminAsync(string username, string password) {
            this.isvalidadminAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isvalidadminAsync(string username, string password, object userState) {
            if ((this.isvalidadminOperationCompleted == null)) {
                this.isvalidadminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisvalidadminOperationCompleted);
            }
            this.InvokeAsync("isvalidadmin", new object[] {
                        username,
                        password}, this.isvalidadminOperationCompleted, userState);
        }
        
        private void OnisvalidadminOperationCompleted(object arg) {
            if ((this.isvalidadminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isvalidadminCompleted(this, new isvalidadminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isvalidmake", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isvalidmake([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isvalidmakeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isvalidmakeResultSpecified) {
            object[] results = this.Invoke("isvalidmake", new object[] {
                        username,
                        password});
            isvalidmakeResult = ((bool)(results[0]));
            isvalidmakeResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isvalidmakeAsync(string username, string password) {
            this.isvalidmakeAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isvalidmakeAsync(string username, string password, object userState) {
            if ((this.isvalidmakeOperationCompleted == null)) {
                this.isvalidmakeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisvalidmakeOperationCompleted);
            }
            this.InvokeAsync("isvalidmake", new object[] {
                        username,
                        password}, this.isvalidmakeOperationCompleted, userState);
        }
        
        private void OnisvalidmakeOperationCompleted(object arg) {
            if ((this.isvalidmakeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isvalidmakeCompleted(this, new isvalidmakeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/copyproducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/service")]
        public Product[] copyproducts() {
            object[] results = this.Invoke("copyproducts", new object[0]);
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void copyproductsAsync() {
            this.copyproductsAsync(null);
        }
        
        /// <remarks/>
        public void copyproductsAsync(object userState) {
            if ((this.copyproductsOperationCompleted == null)) {
                this.copyproductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncopyproductsOperationCompleted);
            }
            this.InvokeAsync("copyproducts", new object[0], this.copyproductsOperationCompleted, userState);
        }
        
        private void OncopyproductsOperationCompleted(object arg) {
            if ((this.copyproductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.copyproductsCompleted(this, new copyproductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/calculatediscount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void calculatediscount(int dis, [System.Xml.Serialization.XmlIgnoreAttribute()] bool disSpecified, out int calculatediscountResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool calculatediscountResultSpecified) {
            object[] results = this.Invoke("calculatediscount", new object[] {
                        dis,
                        disSpecified});
            calculatediscountResult = ((int)(results[0]));
            calculatediscountResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void calculatediscountAsync(int dis, bool disSpecified) {
            this.calculatediscountAsync(dis, disSpecified, null);
        }
        
        /// <remarks/>
        public void calculatediscountAsync(int dis, bool disSpecified, object userState) {
            if ((this.calculatediscountOperationCompleted == null)) {
                this.calculatediscountOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculatediscountOperationCompleted);
            }
            this.InvokeAsync("calculatediscount", new object[] {
                        dis,
                        disSpecified}, this.calculatediscountOperationCompleted, userState);
        }
        
        private void OncalculatediscountOperationCompleted(object arg) {
            if ((this.calculatediscountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculatediscountCompleted(this, new calculatediscountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/get_products", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/service")]
        public Product[] get_products() {
            object[] results = this.Invoke("get_products", new object[0]);
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void get_productsAsync() {
            this.get_productsAsync(null);
        }
        
        /// <remarks/>
        public void get_productsAsync(object userState) {
            if ((this.get_productsOperationCompleted == null)) {
                this.get_productsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_productsOperationCompleted);
            }
            this.InvokeAsync("get_products", new object[0], this.get_productsOperationCompleted, userState);
        }
        
        private void Onget_productsOperationCompleted(object arg) {
            if ((this.get_productsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_productsCompleted(this, new get_productsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/service")]
    public partial class Product {
        
        private string productcategoryField;
        
        private string productcompanyField;
        
        private string productnameField;
        
        private string productpriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Productcategory {
            get {
                return this.productcategoryField;
            }
            set {
                this.productcategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Productcompany {
            get {
                return this.productcompanyField;
            }
            set {
                this.productcompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Productname {
            get {
                return this.productnameField;
            }
            set {
                this.productnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Productprice {
            get {
                return this.productpriceField;
            }
            set {
                this.productpriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/service")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AdditemsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddcustomerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddadminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddmakeupartistCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void isvalidcustCompletedEventHandler(object sender, isvalidcustCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isvalidcustCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isvalidcustCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isvalidcustResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isvalidcustResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void isvalidadminCompletedEventHandler(object sender, isvalidadminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isvalidadminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isvalidadminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isvalidadminResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isvalidadminResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void isvalidmakeCompletedEventHandler(object sender, isvalidmakeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isvalidmakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isvalidmakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isvalidmakeResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isvalidmakeResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void copyproductsCompletedEventHandler(object sender, copyproductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class copyproductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal copyproductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void calculatediscountCompletedEventHandler(object sender, calculatediscountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculatediscountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculatediscountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int calculatediscountResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool calculatediscountResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void get_productsCompletedEventHandler(object sender, get_productsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_productsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_productsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591